### ISSUE TITLE
Pocketwatch test bugged

### ISSUE THREAD

**Issue by antontimmermans** [antontimmermans/MOMCDM#1]
Found by @Zcaalock.
reported on Discord.
Which version of Valkyrie are you using?

**Comment by zcaalock** [comment]
newest version

**Comment by antontimmermans** [comment]
I cannot reproduce this problem.
From the code it should work.
I checked it also on the latest valkyrie version, and it works there as expected.

****SPOILERALERT****


if you enter value 2 or higher you will get the pocket watch

**Comment by zcaalock** [comment]
I’ll try it again on different computer when I get home

**Comment by zcaalock** [comment]
i found out that i didn`t have the last version installed. now the watch event is working as intended

**Comment by antontimmermans** [comment]
thx for the confirmation. closing the issue
