### ISSUE TITLE
Translation into Spanish

### ISSUE THREAD

**Issue by antontimmermans** [antontimmermans/MOMCDM#10]
I have prepared a google spreadsheet document with the prepared column for the Spanish translation. https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462
I need your email address to grant you access to edit the file. For more privacy, you can send that in a Private Message on discord (brotim).

It contains (draft) translations from google translate. You can edit the text in this spreadsheet to make a proper translation. All the cells containing text that start with google: need verification or translation.
You can signal me when you confirmed or translated all Spanish text. I will then make the localization.txt file for it.

Tips and tricks for translation can be found in the manual: https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit

**Comment by vidimus** [comment]
Thanks for answering so quickly. I used the spreadsheet for a previous translation (A glimpse of the past) and I also was very satisfied with this method.

I've sent you a request for accessing to the file. I guess you will find out very easily that it's mine.

**Comment by antontimmermans** [comment]
I cannot find any request for editing the doc. how/where did you request it?

**Comment by keros17** [comment]
I didn't see it, sorry ^^

**Comment by vidimus** [comment]
> I cannot find any request for editing the doc. how/where did you request it?

Directly trying to access to the file.  I guess it sends the request to your gmail.com account (the one you used to create the spreadsheet.

**Comment by gustavoberman** [comment]
Hi there!
I can help with spanish translation

**Comment by antontimmermans** [comment]
Great, if I get your request or email (direct message Brotim on discord) I will add you as an editor to the translation spreadsheet.

**Comment by antontimmermans** [comment]
you should be able to editit using this link: https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit?usp=sharing

**Comment by vidimus** [comment]
I've uploaded my initial work with the translation. It's only 10-15% of the total, but I added to the spreadsheets just to see the progress. I'm making the task in a copy of the original spreadsheet just to be more comfortable working with it. 

> Hi there!
> I can help with spanish translation

I would really appreciate some help with the text review. You can test the translation and give me some feedback about typos, incoherences, etc.

**Comment by keros17** [comment]
Are you sure you uploaded it? I'm only seeing lines 1176 to 1188 and  1212 to 1237 translated...

**Comment by vidimus** [comment]
> Are you sure you uploaded it? I'm only seeing lines 1176 to 1188 and 1212 to 1237 translated...

Yeah, I'm pretty sure ;-) . I'm doing the translation of "Chapeldown manor" scenario, not "Disturbance at the docks" one.
I've updated today the translation. It's only a small percentage added, but now there's a little less to finish.

**Comment by keros17** [comment]
Oh ok. I was talking about another scenario xD sorry =P

**Comment by vidimus** [comment]
"Chapel Down Manor" Spanish translation almost finished (less than 20 entries to go). Then I will have to check and review it carefully to avoid incoherences or typos.

**Comment by antontimmermans** [comment]
I can see the great progress... i am looking forward to the end result.
You can also turn the google sheet into a localization.spanish.txt file so you can test it in the valkyrie app. How it is done is also explained in the manual (see link in top of this ticket).  
Let me know if you need help with that.

**Comment by vidimus** [comment]
Chapel Down Manor scenario is ready! Any feedback is welcome!

**Comment by antontimmermans** [comment]
Coming weekend (Feb 8th) this translation will be published. I am waiting for the confirmation that French translation is also ready so I can publish both in one release

**Comment by antontimmermans** [comment]
The translation is released in V1.10 (and already has some Spanish plays). Thank you very much for your effort. I will close this issue. 

Any future updates or improvements can be tracked in a new ticket.

**Comment by antontimmermans** [comment]
@vidimus it appears that something went wrong in the Spanish translation column of https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462
In the document history, I see happening on March 15th 14:26  with your update; cells from 101 and down are empty. I can restore the version from the day before but that will undo the improvements you made in the other text. Do you want to copy the remaining part of your updated translation in it too? Or shall I just roll back changes to the last complete version?

**Comment by keros17** [comment]
I think if this happened yesterday it’s better to roll back to the last version

I don’t know what happened, I didn’t change anything...

De: Anton<mailto:notifications@github.com>
Enviat: lunes, 16 de marzo de 2020 16:59
Per a: antontimmermans/MOMCDM<mailto:MOMCDM@noreply.github.com>
A/c: Keros<mailto:keros_17@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Tema: Re: [antontimmermans/MOMCDM] Translation into Spanish (#10)


@vidimus<https://github.com/vidimus> it appears that something went wrong in the Spanish translation column of https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462
In the document history, I see happening on March 15th 14:26 with your update; cells from 101 and down are empty. I can restore the version from the day before but that will undo the improvements you made in the other text. Do you want to copy the remaining part of your updated translation in it too? Or shall I just roll back changes to the last complete version?

**Comment by vidimus** [comment]
> @vidimus it appears that something went wrong in the Spanish translation column of https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462
> In the document history, I see happening on March 15th 14:26 with your update; cells from 101 and down are empty. I can restore the version from the day before but that will undo the improvements you made in the other text. Do you want to copy the remaining part of your updated translation in it too? Or shall I just roll back changes to the last complete version?

Hello, Anton.
I don't know what happened (I usually copy the column from my spreadsheet). Anyway, I've copy-paste again the whole column with the Spanish translation.
Sorry for any inconvenience.

**Comment by keros17** [comment]
I think you can restore it without any problem.

Thanks Anton ^^



Enviat des del meu telèfon intel·ligent Samsung Galaxy.



-------- Missatge original --------
De: vidimus <notifications@github.com>
Data: 16/3/20 22:35 (GMT+01:00)
A: antontimmermans/MOMCDM <MOMCDM@noreply.github.com>
Ac: Keros <keros_17@hotmail.com>, Comment <comment@noreply.github.com>
Assumpte: Re: [antontimmermans/MOMCDM] Translation into Spanish (#10)


@vidimus<https://github.com/vidimus> it appears that something went wrong in the Spanish translation column of https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462
In the document history, I see happening on March 15th 14:26 with your update; cells from 101 and down are empty. I can restore the version from the day before but that will undo the improvements you made in the other text. Do you want to copy the remaining part of your updated translation in it too? Or shall I just roll back changes to the last complete version?

Hello, Anton.
I don't know what happened (I usually copy the column from my spreadsheet). Anyway, I've copy-paste again the whole column with the Spanish translation.
Sorry for any inconvenience.

**Comment by vidimus** [comment]
Hello, @antontimmermans 
Yesterday at night I replaced the whole column. It should be ok now.

**Comment by keros17** [comment]
Ok thanks ^^

________________________________
De: vidimus <notifications@github.com>
Enviat el: Tuesday, March 17, 2020 11:40:55 PM
Per a: antontimmermans/MOMCDM <MOMCDM@noreply.github.com>
A/c: Keros <keros_17@hotmail.com>; Comment <comment@noreply.github.com>
Tema: Re: [antontimmermans/MOMCDM] Translation into Spanish (#10)


Hello, @antontimmermans<https://github.com/antontimmermans>
Yesterday at night I replaced the whole column. It should be ok now.

**Comment by antontimmermans** [comment]
ready to re-publish?

**Comment by keros17** [comment]
Well... we are in quarantine here but i have to study at same time so xD

________________________________
De: Anton <notifications@github.com>
Enviat el: Wednesday, March 18, 2020 10:56:51 AM
Per a: antontimmermans/MOMCDM <MOMCDM@noreply.github.com>
A/c: Keros <keros_17@hotmail.com>; Comment <comment@noreply.github.com>
Tema: Re: [antontimmermans/MOMCDM] Translation into Spanish (#10)


ready to re-publish?

**Comment by antontimmermans** [comment]
same here, not full lockdown but strongly advised to work from home. 

Bad situation this Corona.. but on the bright side, I am working on a new scenario for which I get a nice idea now... What if this outbreak was the result of a cult successfully conjuring a curse from the elders and investigators have to find a cure

**Comment by keros17** [comment]
Jajaja that's nice idea

Interesting to see how it continues ;p



Enviat des del meu telèfon intel·ligent Samsung Galaxy.



-------- Missatge original --------
De: Anton <notifications@github.com>
Data: 18/3/20 11:03 (GMT+01:00)
A: antontimmermans/MOMCDM <MOMCDM@noreply.github.com>
Ac: Keros <keros_17@hotmail.com>, Comment <comment@noreply.github.com>
Assumpte: Re: [antontimmermans/MOMCDM] Translation into Spanish (#10)


same here, not full lockdown but strongly advised to work from home.

Bad situation this Corona.. but on the bright side, I am working on a new scenario for which I get a nice idea now... What if this outbreak was the result of a cult successfully conjuring a curse from the elders and investigators have to find a cure

**Comment by vidimus** [comment]
> ready to re-publish?

At will, Anton.
