### ISSUE TITLE
Chapel Down Manor - Localized to Portuguese

### ISSUE THREAD

**Issue by Revokee** [antontimmermans/MOMCDM#13]
Hi @antontimmermans,

I saw an old issue in Valkyrie where you point out to this repo, I'm adding the original issue for "Chapel Down Manor" below, where you can find the localized file for Portuguese.
 
https://github.com/NPBruce/valkyrie/issues/1277

I plan to add the voices today.

**Comment by antontimmermans** [comment]
Hi Eduardo,

Thank you for making the Portuguese translation for Chapel Down Manor. I will integrate the file as soon as possible.

I will let you know when that is done.

Best regards,
Anton.

**Comment by antontimmermans** [comment]
I added your translation to the translation overview https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462

The text file is integrated I will wait with publishing until you have completed the voiceover files. (or when you signal it can be released)

**Comment by Revokee** [comment]
Perfect, I pasted in the Spreadsheet above some minor adjustments that I noticed that could be improved during the audio recording.

Here are the audio files.

Feel free to publish everything.

[Audios.zip](https://github.com/antontimmermans/MOMCDM/files/4568205/Audios.zip)

**Comment by antontimmermans** [comment]
Thank you so much for this awesome contribution. The updated translation and the audio files are released in V1.14.
I posted announcements of this fantastic work on Discord Valkyrie Portuguese translation channel and on https://boardgamegeek.com/thread/2100734/valkyrie-home-brew-scenarios-statistics-announceme/page/15

**Comment by antontimmermans** [comment]
text and audio files integrated in version 1.4, closing the issue
