### ISSUE TITLE
Italian translation 

### ISSUE THREAD

**Issue by delborgoem** [antontimmermans/MOMCDM#14]
Hi antontimmermans! :) I could start working on an Italian translation if needed. Let me know :D I'd really like to!

**Comment by antontimmermans** [comment]
Hi @delborgoem ,

Sorry for not noticing your request sooner. Thank you for your offer to translate.

The translation support file is located at https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462

Someone started to translate it into Italian a while ago but never finished it. So I hope you can do the remaining part.

When you are satisfied with the translation you made, you can contact me to integrate the result into the scenario.

Tips for doing a translation can also be found in the manual:https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.h9vwv485yvzz

But if you have questions it is easiest if you contact me on Discord  (Brotim) in the channel where more scenario writers and translators are active https://discord.gg/Cdtp88tq

Best regards,
Anton
