### ISSUE TITLE
Use name token iso color token

### ISSUE THREAD

**Issue by antontimmermans** [antontimmermans/MOMCDM#4]
Howard Bechman: waarom “place black person token” als er een Howard Bechman token is?

**Comment by antontimmermans** [comment]
replaced all color tokens with the appropriate name

**Comment by chrismaliszewski** [comment]
@zcaalock, the next version checked till line 1005: [Localization.Polish.txt](https://github.com/antontimmermans/MOMCDM/files/3073867/Localization.Polish.txt)
