### ISSUE TITLE
Update Polish translation for V1.6

### ISSUE THREAD

**Issue by antontimmermans** [antontimmermans/MOMCDM#6]
[Localization.English.txt](https://github.com/antontimmermans/MOMCDM/files/3414590/Localization.English.txt)

**Comment by chrismaliszewski** [comment]
Hi.

Here is the translation: ~~[Localization.Polish.txt] (https://github.com/antontimmermans/MOMCDM/files/3414730/Localization.Polish.txt)~~ (look below)

A few comments from me:
1. In the line 729 I found a double-space. I'd suggest Search & replace them all.
2. I'm seriously concerned about lines 745-750 of the earlier version of the translation. I have no idea why Polish version doesn't contain Edna's name in the lines. As if you changed the English translation at some point w/o changing Polish or we messed something from the very start :|. It's fixed now but I'm worried if there are other lines like that :|. 
3. **Need help** finding a translation for 'dimensional shambler', ~~Lloigor & Thrall~~ in Polish. Can't find them in the files anywhere. There may not be I am starting to think.

PS. I haven't checked if the translation works. Can you run it and confirm?

**Comment by chrismaliszewski** [comment]
Found Thrall and Lloigor. 

[Localization.Polish.txt](https://github.com/antontimmermans/MOMCDM/files/3414738/Localization.Polish.txt)

**Comment by antontimmermans** [comment]
> Hi.
> 
> Here is the translation: ~[Localization.Polish.txt] (https://github.com/antontimmermans/MOMCDM/files/3414730/Localization.Polish.txt)~ (look below)
> 
> A few comments from me:
> 
> 1. In the line 729 I found a double-space. I'd suggest Search & replace them all.

Done.. thx for pointing them out

> 2. I'm seriously concerned about lines 745-750 of the earlier version of the translation. I have no idea why Polish version doesn't contain Edna's name in the lines. As if you changed the English translation at some point w/o changing Polish or we messed something from the very start :|. It's fixed now but I'm worried if there are other lines like that :|.

Dont'worry this was the biggest change. In the 1.5 version the rune carving was linked to something Edna did. Now it is linked to solving a puzzle. So its perfectly OK.

> 3. **Need help** finding a translation for 'dimensional shambler', ~Lloigor & Thrall~ in Polish. Can't find them in the files anywhere.
> 
> PS. I haven't checked if the translation works. Can you run it and confirm?

Will do. 
Thx for quick action.

**Comment by antontimmermans** [comment]
tested and works fine.
