### ISSUE TITLE
Voice files

### ISSUE THREAD

**Issue by Steve-racer** [antontimmermans/MOMCDM#8]
Here's the VO from Stephen Weese, with Ambria Schneider as Ellie.

[chapel.zip](https://github.com/antontimmermans/MOMCDM/files/3907511/chapel.zip)
[chapelv2.docx](https://github.com/antontimmermans/MOMCDM/files/3907512/chapelv2.docx)

**Comment by antontimmermans** [comment]
integrated in v1.9
