### ISSUE TITLE
Translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by matBonet** [antontimmermans/MOMCDM#9]
I'm interested in translating this scenario into Brazilian Portuguese, how can I go about it?

**Comment by antontimmermans** [comment]
Thank you for choosing this scenario to translate.

For translations there are 3 methods described in this manual starting on page 178
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit?usp=sharing

1. With the Valkyrie app.
2. step 1 + With a plain (sourcecode) text editor; I recommend the Atom (free)
3. using all of the above including MS excel or the free google spreadsheets

Number three (starting on page 184) sounds most complicated but the guy who made the polish translation for this scenario was very happy with this method.

The end result will be that you create a localization.portuguese.txt file that you can attach to this ticket. I will then integrate this back into the scenario.

Let me know if you need help with any of these steps (for example extraction of the localization.english.txt or the set-up of the spreadsheet).

**Comment by antontimmermans** [comment]
I have prepared a google spreadsheet document with the prepared column for the Portuguese translation. https://docs.google.com/spreadsheets/d/1oEIHOoXJMh-uq9eLGHsnwnFTcvwljAs15xkD99hp5FI/edit#gid=655478462
 **I need your email address** to grant you access to edit the file. For more privacy, you can send that in a Private Message on discord (brotim).

It contains (draft) translations from google translate. You can edit the text in this spreadsheet to make a proper translation.  All the cells containing text that start with **_google:_** need verification or translation. 
You can signal me when you confirmed or translated all Portuguese text. I will then make the localization.txt file for it.

**Comment by Revokee** [comment]
Hi @matBonet - I created a localization group for Valkyrie, Chapel Down Manor was localized but we still need help for other scenarios, including "Disturbance at the Docks", also created by @antontimmermans.

You can find our group here: https://chat.whatsapp.com/CBXGr920bOlJlVmxZeaH4v

I can help with the "How To" there.

**Comment by antontimmermans** [comment]
for translation of Disturbance at the docs to Portuguese you can refer to this ticket: https://github.com/antontimmermans/MOMDATD/issues/21

**Comment by antontimmermans** [comment]
In ticket https://github.com/antontimmermans/MOMCDM/issues/13 you can find the latest status of the Portuguese translation.

**Comment by antontimmermans** [comment]
For finding support from valkyrie developers and translators I can strongly recommend Valkyrie Discord https://discord.gg/wp5nn2 (free account, can be used web-based or via app)

There are channels for translations for various languages, but not for Portuguese yet. You can ask for a specific Portuguese translation channel in the general chat channel.
The advantage is that there are many users on the Valkyrie Discord and probably more Portuguese speakers that can help with translations.
